---
title: "Final Project"
author: "Ethan Gutterman, Joshua Aguilar, Kaden Emerson, Dominic Tangaan"
format: 
  html:
    embed-resources: true
    code-tools: true
    toc: true
    number-sections: true
editor: source
execute: 
  error: true
  echo: true
  message: false
  warning: false
---

```{r, setup}
library(tidyverse)
poverty_data<-read_csv("extreme_poverty_percent_people_below_215_a_day.csv")

footprint_date<-read.csv("matfootp_cap.csv")

```

```{r}
poverty_data <- poverty_data |>
  select(country, "1970":"2019") |>
  pivot_longer(cols = "1970":"2019",
               names_to = "year",
               values_to = "% people below $2.15 a day")
```

```{r}
footprint_date <- footprint_date |>
  rename_with(~ str_remove(., "^X")) |>
  pivot_longer(cols = "1970":"2019",
               names_to = "year",
               values_to = "material footprint per capita (tonnes)") |>
  full_join(poverty_data, join_by(country, year)) |>
  filter(!is.na(`% people below $2.15 a day`)) |>
  filter(!is.na(`material footprint per capita (tonnes)`)) |>
  mutate(`% people below $2.15 a day` =
           as.numeric(`% people below $2.15 a day`)) |>
  mutate(`material footprint per capita (tonnes)` =
           as.numeric(`material footprint per capita (tonnes)`))
```

